# https://www.lxkaka.wang/
version: '2'

services:
  jaeger-agent:
    image: jaegertracing/jaeger-agent
    hostname: jaeger-agent
    command: ["--collector.host-port=collector-host:14267"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: on-failure
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    networks:
      - default

  elasticsearch:
    image: elasticsearch
    hostname: es-host

  jaeger-collector:
    image: jaegertracing/jaeger-collector
    ports:
      - "14269:14269"
      - "14268:14268"
      - "14267:14267"
      - "9411:9411"
    networks:
      - default
    restart: on-failure
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: [
      "--es.server-urls=http:es-host:9200",
      "--log-level=debug"
      ]
    depends_on:
      - elasticsearch

  jaeger-query:
    image: jaegertracing/jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - no_proxy=localhost
    ports:
      - "16686:16686"
      #- "16687:16687"
    networks:
      - default
    restart: on-failure
    command: [
      "--es.server-urls=http://es-host:9200",
      "--span-storage.type=elasticsearch",
      "--log-level=debug",
      #"--query.static-files=/go/jaeger-ui/"
      ]
    depends_on:
      - jaeger-collector
networks:
  elastic-jaeger:
      driver: bridge
