version: '3.1'

services:

  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
    //restart: always

  kibana:
    image: kibana
#    container_name: kibana
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    //restart: always

#  logstash:
#    image: logstash
#    links:
#      - elasticsearch
#    depends_on:
#      - kibana
#    restart: always
