version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper
    restart: unless-stopped
  kafka:
    image: wurstmeister/kafka
    volumes:
      - /etc/localtime:/etc/localtime               ## 挂载位置（kafka镜像和宿主机器之间时间保持一直）
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost         ## 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"       ## 卡夫卡运行是基于zookeeper的
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "stream-in:1:1,stream-out:1:1"
    depends_on:
      - zookeeper                                   ## 启动web容器时，检查依赖depends_on的配置内容，先启动db和redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: kafka
    restart: always
